### ISSUE TITLE
Can't create a key

### ISSUE THREAD

**Issue by mbanusic** [duanestorey/juniper-author#3]
I am getting this error:

```
2024/12/24 09:34:52 [error] 1791278#1791278: *11240936 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty in /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/XML.php:144
Stack trace:
#0 /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/XML.php(144): DOMDocument->loadXML()
#1 /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/XML.php(74): phpseclib3\Crypt\EC\Formats\Keys\XML::isolateNamespace()
#2 /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php(150): phpseclib3\Crypt\EC\Formats\Keys\XML::load()
#3 /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php(39): phpseclib3\Crypt\Common\AsymmetricKey::load()
#4 /var/www/plugins/wp-content/plugins/juniper-author/vendor/phpseclib/phpseclib/php" while reading response header from upstream, client: 93.139.156.194, server: plugins.nezn.am, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "plugins.nezn.am", referrer: "https://plugins.nezn.am/wp-admin/options-general.php?page=juniper"
```

WP: 6.7.1
PHP: 8.1

**Comment by duanestorey** [comment]
Did yoy try setting a password when you clicked to generate it?  I haven't seem that error before.

**Comment by mbanusic** [comment]
The error occurs when trying to setup signing key here: wp-admin/admin.php?page=juniper, but the Authorship information hasn't been set here: wp-admin/admin.php?page=juniper-options. The first link is what is linked from plugin screen as Settings and is first in menu, so my mistake was thinking that should be a first step. Just change the order and to what links and it will work.

**Comment by duanestorey** [comment]
I changed this around, it should be addressed in the next release.  Thanks.
